# Change these first
owner: liquibase # Your GitHub organization or username, where this repository lives
repo: liquibase-io-status # The name of this repository

sites:
  - name: Liquibase.io API
    url: $LIQUIBASE_IO_API_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000
  - name: Liquibase.io WEB
    url: $LIQUIBASE_IO_MAIN_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000
  - name: Liquibase.io Runner
    url: $LIQUIBASE_IO_RUNNER_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000
  - name: Liquibase.io Dispatcher
    url: $LIQUIBASE_IO_DISPATCHER_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000
  - name: Liquibase.io Connection Tester
    url: $LIQUIBASE_IO_CONNECTION_TESTER_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000

assignees: # Users to assign downtime issues (optional)
  - jandroav

skipDeleteIssues: true

status-website:
  theme: dark
  favicon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.png
  faviconSvg: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.liquibase.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_white.svg
  name: Status
  introTitle: "Current Status"
  introMessage: "Monitor availability and performance of Liquibase.io"
  js: |
    function convertDatesToUTC() {
      // Convert DD elements (existing functionality)
      const dateElements = document.querySelectorAll('dd');
      dateElements.forEach(el => {
        if (el.innerText.includes('/')) {
          const date = new Date(el.innerText);
          el.innerText = date.toUTCString().replace('GMT', 'UTC');
        }
      });

      // Convert incident times
      const incidentElements = document.querySelectorAll('.f div div');
      incidentElements.forEach(el => {
        const text = el.innerText;
        if (text.includes('Opened at')) {
          const dateStr = text.match(/Opened at (.*?) with/)[1];
          const date = new Date(dateStr);
          el.innerText = text.replace(dateStr, date.toUTCString().replace('GMT', 'UTC'));
        }
      });
    }
    
    document.addEventListener('DOMContentLoaded', function() {
      // Initial conversion
      convertDatesToUTC();
      
      // Set up observer only after DOM is ready
      const targetNode = document.body;
      if (targetNode) {
        const observer = new MutationObserver(convertDatesToUTC);
        observer.observe(targetNode, { 
          childList: true, 
          subtree: true,
          characterData: true 
        });
      }
    });
  customHeadHtml: |
    <style>
      dd { font-family: monospace; }
    </style>

user-agent: "liquibot"

i18n:
  footer: © 2025 Liquibase
