# Change these first
owner: liquibase # Your GitHub organization or username, where this repository lives
repo: liquibase-io-status # The name of this repository

sites:
  - name: Liquibase IO API
    url: $LIQUIBASE_IO_API_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000
  - name: Liquibase IO WEB
    url: $LIQUIBASE_IO_MAIN_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000
  - name: Liquibase IO Runner
    url: $LIQUIBASE_IO_RUNNER_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000
  - name: Liquibase IO Dispatcher
    url: $LIQUIBASE_IO_DISPATCHER_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000
  - name: Liquibase IO Connection Tester
    url: $LIQUIBASE_IO_CONNECTION_TESTER_URL
    icon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
    maxResponseTime: 7000

assignees: # Users to assign downtime issues (optional)
  - jandroav

skipDeleteIssues: true

status-website:
  navbar:
    - title: History
      href: /#history
  theme: light
  favicon: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.png
  faviconSvg: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_fav.svg
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.liquibase.io
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/liquibase/liquibase-io-status/master/static/img/liquibase_teal.svg
  name: Status
  introTitle: "Current Status"
  introMessage: "Monitor availability and performance of Liquibase IO"
  js: |
    (function() {
      function addPastIncidentsId() {
        const h2Elements = document.querySelectorAll('h2.svelte-18y4uo2');
        for (const h2 of h2Elements) {
          if (h2.textContent === 'Past Incidents') {
            h2.id = 'history';
            break;
          }
        }
      }

      function convertDatesToUTC() {
        requestAnimationFrame(() => {
          // Convert dates in dd elements
          const dateElements = document.querySelectorAll('dd');
          dateElements.forEach(el => {
            if (el.innerText.includes('/')) {
              const date = new Date(el.innerText);
              el.innerText = date.toUTCString().replace('GMT', 'UTC');
            }
          });

          // Convert dates in incident headers
          const incidentDivs = document.querySelectorAll('div.f div');
          incidentDivs.forEach(div => {
            const text = div.innerText;
            if (text.includes('Opened at')) {
              const dateStr = text.match(/Opened at (.*?) with/)?.[1];
              if (dateStr) {
                const date = new Date(dateStr);
                div.innerText = text.replace(dateStr, date.toUTCString().replace('GMT', 'UTC'));
              }
            }
          });
        });
      }

      // Wait for document load without blocking
      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initObserver);
      } else {
        initObserver();
      }

      function initObserver() {
        convertDatesToUTC();
        addPastIncidentsId();
        const observer = new MutationObserver((mutations) => {
          convertDatesToUTC();
          addPastIncidentsId();
        });
        observer.observe(document.body, {
          childList: true,
          subtree: true,
          characterData: true
        });
      }
    })();
  customHeadHtml: |
    <style>
    
      /* io style */
      dd { font-family: Inter, sans-serif; !important }
      body { font-family: Inter, sans-serif; !important }
      h1 { 
        font-family: Inter, sans-serif !important;
        font-weight: 400 !important;
        font-size: 34px !important;
        letter-spacing: 0.25px !important;
        line-height: 1.235 !important;
      }
      h2, h3, h4, h5, h6 { 
        font-family: Inter, sans-serif !important;
        font-weight: 400 !important;
        letter-spacing: 0.25px !important;
        line-height: 1.235 !important;
      }
      /* io style */
    
      html {
        scroll-padding-top: 70px; /* Adjust based on your header height */
      }

      /* Add navbar styling */
    .container.svelte-a08hsz.svelte-a08hsz {
      justify-content: left !important;
    }

    section article.down,
    section.live-status article.down,
    article.down.down-active {
      border-color: var(--down-border-left-color) !important;
      background: var(--down-background-color) !important;
    }

    article.degraded,
    section article.degraded,
    main article.degraded.degraded-active,
    section article.degraded.link {
      border-color: #808080 !important;
      background: #A9A9A9 !important;
    }

    /* Hide specified div elements */
    article.down:nth-child(1) > div:nth-child(2),
    article.down:nth-child(1) > div:nth-child(3),
    article.down:nth-child(2) > div:nth-child(2),
    article.down:nth-child(2) > div:nth-child(3),
    article.down:nth-child(3) > div:nth-child(2),
    article.down:nth-child(3) > div:nth-child(3),
    article.down:nth-child(4) > div:nth-child(2),
    article.down:nth-child(4) > div:nth-child(3),
    article.down:nth-child(5) > div:nth-child(2),
    article.down:nth-child(5) > div:nth-child(3),
    article.up:nth-child(1) > div:nth-child(2),
    article.up:nth-child(1) > div:nth-child(3),
    article.link:nth-child(2) > div:nth-child(2),
    article.link:nth-child(2) > div:nth-child(3),
    article.up:nth-child(3) > div:nth-child(2),
    article.up:nth-child(3) > div:nth-child(3),
    article.up:nth-child(4) > div:nth-child(2),
    article.up:nth-child(4) > div:nth-child(3),
    article.up:nth-child(5) > div:nth-child(2),
    article.up:nth-child(5) > div:nth-child(3) {
      display: none;
    }

    /* Make h4 links not clickable */
    article.up:nth-child(1) > h4:nth-child(1) > a:nth-child(2),
    article.link:nth-child(2) > h4:nth-child(1) > a:nth-child(2),
    article.up:nth-child(3) > h4:nth-child(1) > a:nth-child(2),
    article.up:nth-child(4) > h4:nth-child(1) > a:nth-child(2),
    article.up:nth-child(5) > h4:nth-child(1) > a:nth-child(2) {
      pointer-events: none;
      text-decoration: none;
      color: inherit;
      cursor: default;
    }

    /* Hide backgrounds for service status sections */
    section h4,
    section h4 a.svelte-fqsq6s,
    section div .data.svelte-fqsq6s,
    section div {
      background: transparent !important;
    }

    /* Remove any potential background from parent containers */
    section.live-status article,
    section.live-status article div {
      background: transparent !important;
    }

    /* Hide specific labels in form */
    form.f > div:nth-child(1) > label:nth-child(2),
    form.f > div:nth-child(2) > label:nth-child(2),
    form.f > div:nth-child(3) > label:nth-child(2),
    form.f > div:nth-child(4) > label:nth-child(2),
    form.f > div:nth-child(5) > label:nth-child(2) {
      display: none;
    }

    </style>

user-agent: "liquibot"

i18n:
  footer: © 2025 Liquibase
